# Generated by Django 4.0.6 on 2022-12-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tks', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=155)),
                ('data_a', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_a', models.DateField(auto_now=True)),
                ('data_e', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=11)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carteiras.acao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('faturado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_a', models.DateField(auto_now=True)),
                ('data_e', models.DateField(verbose_name='Data de vencimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_a', models.DateField(auto_now=True)),
                ('valor_inv', models.DecimalField(decimal_places=2, max_digits=11)),
                ('rendimento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tempo', models.CharField(choices=[('DIA', 'Diario'), ('MES', 'Mensal'), ('TRI', 'Trimestral'), ('SEM', 'Semestral'), ('ANO', 'Anual')], max_length=3)),
                ('tipo', models.CharField(choices=[('TED', 'Tesouro Direto'), ('CBD', 'CBD'), ('LCI', ' LCI/LCA'), ('DBT', 'Debêntures'), ('LDC', 'Letras de Câmbio'), ('CRI', 'CRI/CRA'), ('POP', 'Poupança'), ('OTR', 'Outro')], max_length=3)),
                ('descricao_tipo', models.CharField(max_length=155)),
                ('data_e', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('faturado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_a', models.DateField(auto_now=True)),
                ('data_e', models.DateField(verbose_name='Data de vencimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
