# Generated by Django 4.0.6 on 2022-12-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixa',
            old_name='valor_inv',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavel',
            old_name='valor_pago',
            new_name='valor',
        ),
    ]
