# Generated by Django 4.0.6 on 2022-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='tks',
            field=models.CharField(max_length=10),
        ),
    ]
