# Generated by Django 4.0.6 on 2022-10-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0002_alter_acao_tks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variavel',
            name='preco_medio',
        ),
        migrations.AddField(
            model_name='variavel',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variavel',
            name='date_a',
            field=models.DateField(auto_now=True),
        ),
    ]
