# Generated by Django 4.0.6 on 2022-11-24 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carteiras', '0003_remove_variavel_preco_medio_variavel_data_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('faturado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_a', models.DateField(auto_now=True)),
                ('data_e', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('faturado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_a', models.DateField(auto_now=True)),
                ('data_e', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
